### PR TITLE
Reducer unhides relevant editor when line focused

### LINKED ISSUE #812: TypeError in /
## Error in Popcode

**TypeError** in **/**
Uncaught TypeError: Cannot read property 'delete' of undefined

[View on Bugsnag](https://app.bugsnag.com/popcode/popcode/errors/5911b7ef263d9b00180e7829?event_id=5911b7ef263d9b00180e7828&i=gh&m=ci)

## Stacktrace

    webpack:///src/reducers/projects.js:118 - 

[View full stacktrace](https://app.bugsnag.com/popcode/popcode/errors/5911b7ef263d9b00180e7829?event_id=5911b7ef263d9b00180e7828&i=gh&m=ci)

### LINKED ISSUE #827: TypeError in /
## Error in Popcode

**TypeError** in **/**
Uncaught TypeError: Cannot read property 'delete' of undefined

[View on Bugsnag](https://app.bugsnag.com/popcode/popcode/errors/59246995a695330018855e4b?event_id=59246995a695330018855e4a&i=gh&m=ci)

## Stacktrace

    webpack:///src/reducers/projects.js:118 - 

[View full stacktrace](https://app.bugsnag.com/popcode/popcode/errors/59246995a695330018855e4b?event_id=59246995a695330018855e4a&i=gh&m=ci)

### LINKED ISSUE #829: TypeError in /
## Error in Popcode

**TypeError** in **/**
Uncaught TypeError: Cannot read property 'delete' of undefined

[View on Bugsnag](https://app.bugsnag.com/popcode/popcode/errors/5925860ddfa8e500187a8f05?event_id=5925860ddfa8e500187a8f04&i=gh&m=ci)

## Stacktrace

    webpack:///src/reducers/projects.js:17 - 

[View full stacktrace](https://app.bugsnag.com/popcode/popcode/errors/5925860ddfa8e500187a8f05?event_id=5925860ddfa8e500187a8f04&i=gh&m=ci)

### PR DESCRIPTION
**Pull request by outoftime**
Previously the Workspace component’s handler for line focus would dispatch an `unhideComponent` action from the handler for a focused line request.  This had trivially buggy behavior in that it omitted the required first argument to `unhideComponent`, which should have been the current project ID.

However, it also doesn’t follow the recently adopted pattern of reducers knowing what to do in response to actions, rather than procedural code dispatching multiple actions to deal with different aspects of responding to a particular user action or external event.

So, remove the call to `unhideComponent` and instead have the `ui` reducer handle the focus line action.

Also while we’re in there, rename the rather awkward `userRequestedFocusedLine` to `focusLine`, following the convention of using the active voice for user-initiated actions.

Fixes #812 
Fixes #827 
Fixes #829

### CODE REVIEW

**Comment by outoftime** [comment]
@ajgreenb thoughts on this?

**Comment by outoftime** [comment]
N.B. I continue to not love the `reduceRoot` pattern, and note with dismay that this PR expands its usage to some extent.

That this isn’t really a new use case—there is still basically a single purpose for `reduceRoot` in the code, namely getting the current project’s key in order to perform a manipulation on it in the `projects` subtree. This is just another case of that.

There are many other actions that amount to “do something to the current project”, but all of those take the current project’s `projectKey` in the action payload. I don’t think there’s any category difference between the latter actions and the couple that use `reduceRoot`, although it would feel particularly goofy to, for instance, pass a `projectKey` to the `logOut` action. I do recall reading someone smart-sounding recommending doing just this sort of thing in a thread somewhere, though.

Anyway, my preference would either be to get rid of `reduceRoot` or to commit fully to its use (possibly getting rid of `combineReducers` entirely in favor of having all subtree reducers operating on the full tree, with the understanding that each will only modify the part of the tree it has responsibility for). I lean toward the former; it would be very awkward, for instance, that the order in which reducers process the state tree would become significant.

@inlinestyle @ajgreenb @alexpelan @jwang1919 definitely interested in your thoughts on this!

**Comment by jwang1919** [comment]
@outoftime I think I've been too long away from Popcode (or my inexperience with JS 😄). I reread your comments several times and still can't make heads or tails onto what exactly this PR is addressing.

**Comment by outoftime** [comment]
@jwang1919 I feel you. I don’t think this is an area of the code you’ve spent a lot of time in—I’d be happy to give you a higher-level overview of the issue at hand IRL tomorrow if we have a few minutes to chat.

File: src/reducers/projects.js [hunk 1]
```diff
@@ -83,6 +83,21 @@ export function reduceRoot(stateIn, action) {
...
           );
         }
+      case 'FOCUS_LINE':
+        {
+          const currentProjectKey =
+            stateIn.getIn(['currentProject', 'projectKey']);
+
+          if (isNil(currentProjectKey)) {
+            return stateIn;
+          }
```
Comment (ajgreenb) [inline src/reducers/projects.js]: When would a `FOCUS_LINE` action occur with a nil `currentProjectKey`? My impression is that the only time there's not a current project key is when the app is loading.

File: src/reducers/projects.js [hunk 2]
```diff
@@ -83,6 +83,21 @@ export function reduceRoot(stateIn, action) {
...
+
+          return projects.updateIn(
+            [currentProjectKey, 'hiddenUIComponents'],
+            hiddenUIComponents =>
+              hiddenUIComponents.remove(`editor.${action.payload.language}`),
+          );
+        }
```
Comment (ajgreenb) [inline src/reducers/projects.js]: Not sure it matters too much, but would it be worth abstracting this and the logic in the `UNHIDE_COMPONENT` reducer into a single function? Not sure if the DRYness is worth the abstraction overhead in this case, though...

**Comment by ajgreenb** [comment]
So the general idea is that instead of having `_handleErrorClick` dispatch two actions, it just dispatches `FOCUS_LINE`, which gets consumed by two reducers (the `ui` reducer and `reduceRoot`)?

Seems reasonable to me! Especially if you're trying to have components just dispatch single actions that can be handled by multiple reducers.

Is your bone with `reduceRoot` that it allows more-than-required access to the state tree? Does seem like a good pattern to restrict reducers to just the subtrees for which they're responsible.

File: src/reducers/projects.js (hunk 1 above)
Comment (outoftime) [inline src/reducers/projects.js]: Good call—this is overly defensive. I’ll remove it.

File: src/reducers/projects.js (hunk 2 above)
Comment (outoftime) [inline src/reducers/projects.js]: Definitely a good thought—I’m kind of on the fence and am planning a bigger refactor of the reducers very soon, so I’m comfortable with a bit of duplication for now.

**Comment by outoftime** [comment]
@ajgreenb I actually *don’t* have a problem with `reduceRoot` having access to the entire tree—that is the explicit intent, after all. The reasons I’ve grown to dislike the pattern are:

* It’s inconsistently applied (most reducer code is subtree-only)
* If it _were_ consistently applied, the behavior of the system would depend on what order the reducers were run in (reducer B might look at a value in subtree A, which may have been modified by Reducer A in response to the same action, but only if Reducer A ran first)

I think the second issue points at a pretty fundamental problem with the pattern, and is probably the best argument I’ve come across for total isolation.

Another option would be to organize reducers around actions, rather than around subtrees—e.g., one reducer (in its own module) that takes the root tree and does everything it needs to do to handle e.g. `focusLine`. As long as you have only one reducer per action, the order issue goes away. But that seems to be a less common pattern and I like having the subtree reducers be the “authority” on the shape of their subtree (setting up initial state etc.)

**Comment by outoftime** [comment]
@ajgreenb in response to your first question, yes—in general I strive to have actions simply report discrete events (user clicks something, API response returned, etc.) without the dispatching code having an opinion on what should happen. The reducers and sagas should then define how the system reacts to the action. This is a fairly new approach—I’ve just completed overhauling the action creators and introducing sagas to effect it—but I continue to like it much better than the previous pattern of procedurally dispatching multiple actions in response to one event.

File: src/reducers/projects.js (hunk 1 above)
Comment (inlinestyle) [inline src/reducers/projects.js]: Just to check my understanding: if you *were* keeping this line, wouldn't you want to return `projects`, not `stateIn`?

File: src/reducers/projects.js (hunk 2 above)
Comment (inlinestyle) [inline src/reducers/projects.js]: Alternatively - is there a reason this has to be on its own and not be tacked on top of the existing `UNHIDE_COMPONENT` reducer like so?
```
    case 'FOCUS_LINE':
    case 'UNHIDE_COMPONENT':
      return state.updateIn(
        [action.payload.projectKey, 'hiddenUIComponents'],
        hiddenUIComponents =>
          hiddenUIComponents.delete(action.payload.componentName),
      ).setIn(
        [action.payload.projectKey, 'updatedAt'],
        action.meta.timestamp,
      );
```
You'd just have to change `action.payload.language` to `action.payload.componentName` (or vice versa) and consolidate how you're handling `projectKey`. You'd also get the benefit of the `updatedAt` getting properly updated (not sure if that was intentionally left out of the new proposed reducer case or not).

File: src/reducers/projects.js (hunk 1 above)
Comment (outoftime) [inline src/reducers/projects.js]: @inlinestyle yup

File: src/reducers/projects.js (hunk 2 above)
Comment (outoftime) [inline src/reducers/projects.js]: @inlinestyle I actually think changing the action payload structure is a pretty strong argument against this approach—from the perspective of the action, you’ve just asked to focus a particular line of code. It shouldn’t need to know anything about “component names” or even that one of the responses to that action is to maximize the editor component in question.

Comment (outoftime) [inline src/reducers/projects.js]: However that is a good point about the `updatedAt`, so I will go ahead and extract a function that does the right thing.

**Comment by ajgreenb** [comment]
Looks like there are two failing tests, but other than that, LGTM!

**Comment by ajgreenb** [comment]
LGTM

**Comment by outoftime** [comment]
Thanks y’all!
