### PR TITLE
Deprecate mismatched-close-tag into more precise errors

### LINKED ISSUE #562: Misleading error when a closing tag is missing
Submitter: Kate Miller
Here is the code:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
     <h1>My Web Page</h1>
        <p><a href="//google.com">
            Go to Google
    </a>   
    </body>
</html>
```

Here is the error:

```
11
Your <p> tag needs a closing tag, but instead there’s a </body> tag where the </p> tag should be.
```

This error was confusing, because in reading it without thinking about it, my first instinct was to replace the closing body tag with a closing p tag which then of course led me to another error...

```
12
Your <body> tag needs a closing tag, but instead there’s a </html> tag where the </body> tag should be.
```

Which led me to replace the closing html tag with a closing body tag...

I think the wording of that original error is confusing. By saying there is a closing body tag where the closing p tag should be immediately make you think replacement. A better error message might be "closing p tag is missing"

### PR DESCRIPTION
**Pull request by tenyoung795**
An attempt to fix #562, although goes a bit farther by deprecating `mismatched-close-tag` in favor of three distinct errors:

- `misplaced-close-tag`: **(new)** suggests moving a spare unopened close tag
- `unclosed-tag-by-mismatched-close-tag`: **(new)** suggests adding a close tag right before the mismatched close tag
- `unexpected-close-tag`: preexisting

This pull request introduces a new HTML `Validator` that performs its own lexical analysis using the [SAX](https://en.wikipedia.org/wiki/Simple_API_for_XML) parser from [`parse5`](https://github.com/inikulin/parse5) to parse HTML tokens.

The code is a bit complex, so feel free to offer readability suggestions. Thanks!

### CODE REVIEW

**Comment by outoftime** [comment]
@tenyoung795 this is cool as hell!!

I haven’t gone over it in detail yet but one bit of high-level feedback—I think it would be best, instead of thinking of this as a “custom validation”, rather to simply think of it as another validation backend that happens to have been written in-house. In particular, I would propose splitting out the nitty-gritty implementation of the DOM traversal from the adapter code in `src/validators`.

I think the ideal approach would be to create a new NPM module and set it up as a dependency of Popcode (much like [`loop-breaker`](https://github.com/popcodeorg/loop-breaker)). I’d be happy to create a new repo under the `popcodeorg` namespace and make you an owner if you’d like to go that route. As a more practical compromise, I’d also be down to just extract the parsing/traversing code into its own module in the popcode application.

LMK your thoughts!

**Comment by tenyoung795** [comment]
Thanks, @outoftime! :smiley: 

Either an external or internal module sounds good to me, although I wonder what would the module look like? Specifically, what exactly would the module be abstracting out from [`custom.js`](https://github.com/tenyoung795/popcode/blob/b0439b7594d30e71b0def3aba3de0933553f76a7/src/validations/html/custom.js)?

Technically, `CustomValidator` itself performs no parsing but indeed registers various parse-event listeners in various ways. Here is the best API I can think of currently, in pseudocode:

```
interface Rule {
  openTag({name, attributes, selfClosing}, location);
  closeTag(name, location);
  done() => Iterable<Error>;
}

function runRules(source) {
  const parser = ...;
  const rules = ...;
  return new Promise((resolve) => {
    register each rule on parser;
    parser.write(source);
    parser.end(() => {
      resolve(chain all rules' errors);
    });
  });
}
```

Personally, I'd prefer the internal module unless we could very confidently devise an externally useful API; roughly speaking, it's easier to recover from under-design than over-design. If this proves externally useful later on, then it could easily be moved out. Hiding a module back into Popcode would be tricky once an external client exists.

**Comment by outoftime** [comment]
Hey @tenyoung795, I’m convinced by your argument about the lower costs of moving to an external module later rather than moving in the opposite direction. I think the interface you propose above is a good one—specifically I would expect the `validator` to just call the `runRules(source)` function and get back a list of errors (synchronously or asynchronously) and then figure out how to turn the errors into the Popcode format. Seem reasonable?

**Comment by tenyoung795** [comment]
Yep, that sounds reasonable! I'll try to redo the branch and then ping this PR once ready.

(If this takes too long, anyone should feel free to announce their own version of this PR.)

File: src/validations/html/rules/MismatchedTag.js [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+    // Process the remaining errors.
+    for (const [location, {name, mismatchedTags}]
+         of this._mismatchedTagErrorsByLocation) {
+      if (this._unopenedTagLocations.has(location)) {
+        yield {
+          code: Code.UNOPENED_TAG,
+          closeTag: {
+            name,
+            location: {
+              row: location.get('row'),
```
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: According to the `Record` [documentation](https://facebook.github.io/immutable-js/docs/#/Record), `location.row` and `location.column` wouldn't work on IE 8, so this (attempts to) stick to Immutable's API subset that works on IE 8. If Popcode shall not support IE 8, then this could use more idiomatic property access instead.

**Comment by tenyoung795** [comment]
Okay, I think it's ready now!

FYI, I think `runRules` and friends could be used to fix #378. For example, a rule could check the descendant tag names of the `head` element to ensure no content was inside the `head`.

File: src/validations/html/custom.js [hunk 2]
```diff
@@ -0,0 +1,144 @@
+import {List, Map, Record, Set} from 'immutable';
+import {SAXParser} from 'parse5';
+import voidElements from 'void-elements';
+import Validator from '../Validator';
+
+// An immutable.Record wrapper of parse5.MarkupData.Location, whose line and
+// col are 1-indexed.
+const Location = Record({line: 1, col: 1});  // eslint-disable-line new-cap
+
+function findMismatchedCloseTags(parser) {
```
Comment (outoftime) [inline src/validations/html/custom.js]: At a high level, I’d propose restructuring the way you store the state during the tree walk. In particular I would hold on to three collections, each of which corresponds to one of the errors this module can generate:

1. Map of opening tags that don’t have a properly-placed closing tag, and for which we haven’t yet seen a misplaced closing tag, keyed by tag name, with a queue of locations (`unclosed-tag-by-mismatched-close-tag`)
2. Set of pairs of opening/closing tags where the closing tag is in the wrong place (`misplaced-close-tag`)
3. Set of closing tags that don’t match any opening tag (`unexpected-close-tag`)

Any time we encounter a mismatch:

* Add all unclosed tags to collection 1
* If the closing tag we have encountered does not match an opening tag in the stack (`!open`):
  * If the closing tag we have encountered matches an entry in collection 1, remove that entry from collection 1, and add the open/close pair to collection 2
  * Otherwise, add the closing tag to collection 3

Obviously this structure has a lot in common with what you’ve got now, but I think it’ll be easier to reason about. In particular, once the initial tree walk is finished, we have a final accounting of the three error types we can generate—there is no need for a second pass to turn raw observations into specific errors. As a corollary, understanding the entire process requires understanding only the types of errors the module emits; there is no need to additionally understand the structure and intent of a set of intermediate data structures (something I found fairly challenging when taking this code in just now).

Definitely possible I am missing some nuance here that my proposal doesn’t account for, let me know what you think!

File: src/validations/html/custom.js [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+              close: name,
+              misplacement: spareUnopenedTag.location.line,
+            },
+            suppresses: ['unexpected-close-tag'],
+          };
+        } else if (opened) {
+          yield {
+            row: location.get('line') - 1,
+            column: location.get('col') - 1,
+            reason: 'unclosed-tag-by-mismatched-close-tag',
```
Comment (outoftime) [inline src/validations/html/custom.js]: Is there a reason not to just report this as a normal `unclosed-tag`? Is it really useful to include information about where we found a mismatched closing tag? Would it make more sense to still locate the error at the location of the opening tag? (These are all sincere/non-rhetorical questions!)

File: src/validations/html/custom.js [hunk 4]
```diff
@@ -0,0 +1,144 @@
...
+      for (const mismatchedTag of mismatchedTags) {
+        const spareUnopenedTag =
+          unopenedTagQueuesByName.get(mismatchedTag.name, List.of()).first();
+        if (spareUnopenedTag) {
+          unopenedTagQueuesByName = unopenedTagQueuesByName.update(
+            spareUnopenedTag.name, tags => tags.shift());
+
+          yield {
+            row: location.get('line') - 1,
+            column: location.get('col') - 1,
```
Comment (outoftime) [inline src/validations/html/custom.js]: I would make a slightly stronger claim that the location of this error should be the location of the `spareUnopenedTag` rather than the location of the mismatched closing tag, e.g.:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <div>
            <p>
        </div>
        </p> <!-- fundamentally feels like the error is on this line -->
    </body>
</html>
```

I would change the message to e.g. `This closing </p> tag should go before the </div> on line 9`

**Comment by outoftime** [comment]
@tenyoung795 oh man i am just wrapping up a monster detail review of the previous state of the code… let me submit it and see what happens

File: src/validations/html/rules/MismatchedTag.js [hunk 5]
```diff
@@ -0,0 +1,139 @@
+import {List, Map, Record, Set} from 'immutable';
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: What’s the thinking behind using `Immutable` in here rather than plain JavaScript `Object`, `Array`, `Map`, `Set`? I like `Immutable` and obviously it’s deeply baked into the Redux side of the app, but it’s not without its cost (a more verbose API, having to remember to reassign the variable every time you want to modify the collection) and it doesn’t seem like we’re gaining a lot (reassigning immutable variables vs. mutating mutable constants).

File: src/validations/html/rules/MismatchedTag.js [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+import Code from '../rules/Code';
+
+const Location = Record({row: 0, column: 0});  // eslint-disable-line new-cap
+
+export default class {
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: At a high level, I’d propose restructuring the way you store the state during the tree walk. In particular I would hold on to three collections, each of which corresponds to one of the errors this module can generate:

1. Map of opening tags that don’t have a properly-placed closing tag, and for which we haven’t yet seen a misplaced closing tag, keyed by tag name, with a queue of locations (`unclosed-tag-by-mismatched-close-tag`)
2. Set of pairs of opening/closing tags where the closing tag is in the wrong place (`misplaced-close-tag`)
3. Set of closing tags that don’t match any opening tag (`unexpected-close-tag`)

Any time we encounter a mismatch:

* Add all unclosed tags to collection 1
* If the closing tag we have encountered does not match an opening tag in the stack (`!open`):
  * If the closing tag we have encountered matches an entry in collection 1, remove that entry from collection 1, and add the open/close pair to collection 2
  * Otherwise, add the closing tag to collection 3

Obviously this structure has a lot in common with what you’ve got now, but I think it’ll be easier to reason about. In particular, once the initial tree walk is finished, we have a final accounting of the three error types we can generate—there is no need for a second pass to turn raw observations into specific errors. As a corollary, understanding the entire process requires understanding only the types of errors the module emits; there is no need to additionally understand the structure and intent of a set of intermediate data structures (something I found fairly challenging when taking this code in just now).

Definitely possible I am missing some nuance here that my proposal doesn’t account for, let me know what you think!

File: src/validations/html/runRules.js [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+// * optionally,
+//   openTag({row: number, column: number}, {name: string})
+//   to take in open tags that are neither void nor self-closing
+// * optionally,
+//   closeTag({row: number, column: number}, name: string)
+//   to take in close tags
+export default (rules, source) => {
+  const parser = new SAXParser({locationInfo: true});
+  return new Promise((resolve) => {
+    parser.on('startTag', (name, attrs, selfClosing, {line, col}) => {
```
Comment (outoftime) [inline src/validations/html/runRules.js]: `selfClosing` as in `<br />`? That’s no longer a thing in HTML5 (self-closing void elements are valid but the self-closing doesn’t actually do anything; self-closing non-void elements are not valid and are ignored, e.g. `<div />` does not give you an empty div element)

File: src/validations/html/rules/MismatchedTag.js [hunk 8]
```diff
@@ -0,0 +1,139 @@
...
+  openTag(location, {name}) {
+    this._openTagStack = this._openTagStack.push({location, name});
+  }
+
+  closeTag(location, name) {
+    const locationKey = new Location(location);
+
+    const openIndex = this._openTagStack.findLastIndex(
+      openTag => openTag.name === name);
+    const opened = openIndex >= 0;
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: I generally prefer e.g. `isOpened` for boolean variable names

File: src/validations/html/rules/MismatchedTag.js [hunk 9]
```diff
@@ -0,0 +1,139 @@
...
+
+    // Assume any open tags after the matching open tag are mismatched. If the
+    // source is valid HTML, then no other open tags should exist. If no
+    // matching open tag exists, then all open tags are mismatched.
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: Generally I’m against inline comments, as they tend to get out of sync with the actual code and I’m of the opinion that code can and should be written so that its intent is clear without additional comment. In this case, I think it’s quite clear what the next few lines of code are doing!

File: src/validations/html/rules/MismatchedTag.js [hunk 10]
```diff
@@ -0,0 +1,139 @@
...
+  //
+  // so yield UNCLOSED_TAG.
+  //
+  // A mismatched close tag that has yet to be opened means the case
+  //
+  // <div>
+  //   </span>
+  // </div>
+  //
+  // so yield UNOPENED_TAG.
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: This comment is useful but I think it should be module-level documentation rather than an inline comment.

File: src/validations/html/rules/MismatchedTag.js [hunk 11]
```diff
@@ -0,0 +1,139 @@
...
+  //
+  // Note: MISPLACED_CLOSE_TAG suggestions invalidate UNCLOSED_TAG and
+  // UNOPENED_TAG suggestions by moving other mismatched close tags.
+  // Diagnosing UNCLOSED_TAG and UNOPENED_TAG accurately would require another
+  // pass after all the MISPLACED_CLOSE_TAG suggestions are resolved.
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: I *think* my proposed structure above would remove the need for this invalidation step.

File: src/validations/html/rules/MismatchedTag.js (hunk 1 above)
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: @tenyoung795 Popcode doesn’t support _any_ version of IE (because IE doesn’t provide a way to make sandboxed client-side iframes), and even if it did, it sure as heck wouldn’t support IE8 ; )

The source of truth for “what browsers do we support” lives in [`browsers.json`](https://github.com/popcodeorg/popcode/blob/master/config/browsers.json)

File: src/validations/html/rules/MismatchedTag.js [hunk 12]
```diff
@@ -0,0 +1,139 @@
...
+          this._foundMisplacedCloseTag = true;
+          this._unopenedTagQueuesByName = this._unopenedTagQueuesByName.update(
+            spareUnopenedTag.name, tags => tags.shift());
+
+          yield {
+            code: Code.MISPLACED_CLOSE_TAG,
+            openTag: mismatchedTag,
+            closeTag: {
+              name,
+              location: {
```
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: I would make a slightly stronger claim that the location of this error should be the location of the `spareUnopenedTag` rather than the location of the mismatched closing tag, e.g.:

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Page Title</title>
    </head>
    <body>
        <div>
            <p>
        </div>
        </p> <!-- fundamentally feels like the error is on this line -->
    </body>
</html>
```

I would change the message to e.g. `This closing </p> tag should go before the </div> on line 9`

File: src/validations/html/rules/index.js [hunk 13]
```diff
@@ -0,0 +1,50 @@
...
+  [Code.MISPLACED_CLOSE_TAG]: ({openTag, closeTag, match}) => ({
+    reason: 'misplaced-close-tag',
+    payload: {
+      open: openTag.name,
+      close: closeTag.name,
+      misplacement: match.row + 1,
+    },
+  }),
+  [Code.UNCLOSED_TAG]: ({openTag, closeTag}) => ({
+    reason: 'unclosed-tag-by-mismatched-close-tag',
```
Comment (outoftime) [inline src/validations/html/rules/index.js]: Is there a reason not to just report this as a normal `unclosed-tag`? Is it really useful to include information about where we found a mismatched closing tag? Would it make more sense to still locate the error at the location of the opening tag? (These are all sincere/non-rhetorical questions!)

File: src/validations/html/rules/MismatchedTag.js (hunk 5 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: This module uses containers keyed by locations. (AFAIK) the native JavaScript `Map` and `Set` cannot support custom equality for user-defined types. Their keys may be JavaScript objects but the native containers compare them by identity and (AFAIK) do not support custom equality.

So this uses `Map` and `Set` keyed by the `Record` type `Location`. This could've converted the `{row, col}` to string keys but I figured using a more direct `Record` type would be cleaner and more strongly-typed.

File: src/validations/html/rules/MismatchedTag.js (hunk 8 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Done.

File: src/validations/html/rules/MismatchedTag.js (hunk 9 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Okay, it's gone now!

File: src/validations/html/rules/MismatchedTag.js (hunk 10 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Okay; moved it to the top of the file.

**Comment by tenyoung795** [comment]
I meant to address as much feedback as I could but there's a few spots I unintentionally missed (also a few I intentionally missed but need to explain); I'll hopefully get to all that tomorrow so you can withhold review till then!

File: src/validations/html/rules/index.js (hunk 13 above)
Comment (tenyoung795) [inline src/validations/html/rules/index.js]: > Is there a reason not to just report this as a normal `unclosed-tag`?

Not really other than this was based on `mismatched-close-tag` but:

> Is it really useful to include information about where we found a mismatched closing tag?

Hmm, not really, since the error location already shows where the mismatch was found.

> Would it make more sense to still locate the error at the location of the opening tag?

Actually, the `RuleValidator` (and previous versions) always used the location of the closing tag as the error location. But I agree that the closing tag location + the existing `unclosed-tag` message should suffice.

Too much information in an error can easily overload students!

File: src/validations/html/rules/MismatchedTag.js (hunk 1 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Okay, I switched to direct property access.

Tangential: has ScriptEd ever encountered schools that only supported IE? Or were they forced to install to a supported browser?

File: src/validations/html/rules/MismatchedTag.js (hunk 12 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Okay, I reworded `misplaced-close-tag` to the template you described. It originally said the same information but I like your wording better. :smile:

File: src/validations/html/runRules.js (hunk 7 above)
Comment (tenyoung795) [inline src/validations/html/runRules.js]: On `'startTag`, `SAXParser`'s [event listener](http://inikulin.github.io/parse5/classes/saxparser.html#on) takes in a positional `selfClosing` parameter.

Originally, I figured that it would be easier for the `MismatchedTag` rule to throw out whatever self-closing elements (valid or not) that occur. On the other hand, I don't think students would know about self-closing elements (or at least volunteers should probably avoid bringing them up) so for non-void elements, would it be better to assume that the element was intended to be a normal opening tag?

File: src/validations/html/rules/MismatchedTag.js (hunk 5 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: However, I converted `this._openTagStack` from `List` to a native `Array` since `Array` performs naturally well for a stack, the `List` appears to have no advantages.

Meanwhile, `this._unopenedTagQueuesByName` represent queues, and `List` [promises](https://facebook.github.io/immutable-js/docs/#/List) "efficient addition and removal from both the end (`push`, `pop`) and beginning (`unshift`, `shift`)." Therefore, I've kept `List` for the queues.

File: src/validations/html/rules/MismatchedTag.js (hunk 6 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Unfortunately, I think the problem is that the misplaced close tag may appear _before_ its matching open tag.

In other words:

> Any time we encounter a mismatch:
> - If the closing tag we have encountered does not match an opening tag in the stack

...but the close tag may match a _later_ open tag in the stream of tags.

I'm not opposed to three collections that each correspond to one of the three errors, but how could they be used while avoiding this issue?

While drafting this PR, I initially tried a similar approach until I realized this issue, hence the more complex containers.

**Comment by tenyoung795** [comment]
Okay, should be ready for review now!

File: src/validations/html/runRules.js (hunk 7 above)
Comment (outoftime) [inline src/validations/html/runRules.js]: @tenyoung795 I’d say so—that’s how the HTML5 parser treats them, so I think we should too.

File: src/validations/html/rules/MismatchedTag.js (hunk 6 above)
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: Hey @tenyoung795 so are we talking about something like the below?

```html
<body>
This is a paragraph.</p>

<p>Here is another one
</body>
```

In that case I think it’s probably better behavior to just treat this as two errors: first, an unmatched closing tag, then later, an unclosed opening tag. Try the above markup in this branch and see if you agree that the current error is a bit mystifying.

Obviously if a student generates this situation by cut-and-pasting they may have indeed intended to have the closing tag close the opening tag, but in that case I think it’s still better to show the two errors to get the students thinking more directly about what the correct HTML structure is.

File: src/validations/html/rules/MismatchedTag.js (hunk 5 above)
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: @tenyoung795 OK, that’s a good point about custom equality. As far as I can tell you‘re correct that the native data structures can only work on exact object/primitive value equality.

That said, a couple of further thoughts on this:

* The fact that `Immutable` collections do the right thing here is fairly tangential to the core competency of `Immutable`, i.e. being immutable! And my previous observation stands that actually dealing with immutability in this module does make some of the code harder to follow. How about using e.g. [collections.js](https://github.com/montagejs/collections), which provides normal mutable collections but does have the ability to define custom equality for keys?
* If we don’t want to introduce a new library to solve this problem, I think we should be consistent about the type of collections we use—meaning I would advocate changing `_openTagStack` back to an `Immutable.List` to be consistent with everything else.

File: src/validations/html/rules/MismatchedTag.js (hunk 12 above)
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: Looks great!

File: src/validations/html/rules/MismatchedTag.js (hunk 5 above)
Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: (Also I’m pretty skeptical that `Immutable.List` would provide any tangible performance benefits over `Array` for the queue use case here, although I’m certainly down to be proven wrong with a jsperf etc.)

File: src/validations/html/runRules.js (hunk 7 above)
Comment (outoftime) [inline src/validations/html/runRules.js]: That said, putting e.g. `<div />` in the branch right now does correctly generate an error saying that doesn’t work, so maybe 🤷‍♂️

File: src/validations/html/rules/MismatchedTag.js (hunk 6 above)
Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: > in that case I think it’s still better to show the two errors to get the students thinking more directly about what the correct HTML structure is.

Actually @outoftime, are two errors better even if the close tag proceeds the open tag?

```html
    <body>
        This is a paragraph.<p>

        Here is another one
    </body>
    </p>
```

image

Would these two errors be enough to let the average student realize that they misplaced the close tag? e.g. A `<p>` tag needs to be closed by a `</p>` tag, and I have a `</p>` that doesn't match any `<p>` tag; so I need to move that unmatched `</p>` to close the unclosed `<p>` tag.

If so, I'd be happy to get rid of the `misplaced-close-tag` handling, which would significantly reduce complexity.

Comment (outoftime) [inline src/validations/html/rules/MismatchedTag.js]: @tenyoung795 I definitely think the `misplaced-close-tag` error is an indispensable part of the functionality in this PR, but I think my proposed structure handles the example you give here, specifically:

> If the closing tag we have encountered matches an entry in collection 1, remove that entry from collection 1, and add the open/close pair to collection 2

Am I thinking about it wrong?

Comment (tenyoung795) [inline src/validations/html/rules/MismatchedTag.js]: Provided we only find misplaced closing tags after an open tag, I got a very similar algorithm to work:

- If the closing tag we have encountered matches an opening tag in the stack, add all unclosed tags to collection 1.
- Otherwise:
  - If the closing tag we have encountered matches an entry in collection 1, remove that entry from collection 1, and add the open/close pair to collection 2
  - Otherwise, add the closing tag to collection 3

I think adding all mismatches to collection 1, regardless of whether the mismatch already qualifies for either collection 2 or collection 3, leads to spurious unclosed tag errors since collection 2 or 3 would already "explain" that unclosed tag.

**Comment by tenyoung795** [comment]
Okay @outoftime, after almost a month (I went into a bit of a vacation) it's ready again!

**Comment by outoftime** [comment]
@tenyoung795 awesome! releasing now!

**Comment by tenyoung795** [comment]
Yay, thanks! :smiley:
